### ISSUE TITLE
Forking vs Branching

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/front-end#100]
Traditionally, we've encouraged forking a repo and pushing code changes to your own fork. I've been finding it's increasingly frustrating to review and collaborate using forks, rather than branches. 

For something complicated, like the Featured Content Module, that requires a lot of back and forth and testing, it's resulted in the PR being open for two months. For reviews, if the contributor didn't branch in their fork, you have add the other fork as a remote, then either overwrite the local `gh-pages` branch or use a non-standard name and remember what it was supposed to point to. 

On the other side, [Voltrazord](https://github.com/cfpb/capital-framework/tree/voltrazord) is a branch that anyone can easily test or contribute to without jumping through hoops.

Is there a compelling reason we shouldn't be encouraging our team to branch and push to the repo rather than fork?

**Comment by awolfe76** [comment]
https://twitter.com/holman/status/661356917172793345

**Comment by KimberlyMunoz** [comment]
I just want to also pipe in that as we get closer to the holidays and folks are taking time off, it's easier to pick up where someone left off on branches.

I use forks because that seemed to be the standard, but I think moving to branches might be a better way to move forward on some of the larger team projects like Capital Framework.

**Comment by Scotchester** [comment]
Though painful to do it through Twitter's interface, lots of interesting discussion off that Holman tweet. One thing people pointed out is that if you're working with gh-pages, since only the gh-pages branch publishes, using forks is essential for live-previewing updates. Running Jekyll locally can mitigate this somewhat, but getting the environment working and matching what GH is currently running can be painful, especially for non-devs. (I recently tried to set this up for Natalia and a bug in one of the Ruby dependencies prevented the `bundle install` from completing.)

As far as I'm concerned, I'm happy to let this be decided on a team-by-team basis, as with the decision of who merges PRs.

**Comment by jimmynotjim** [comment]
@Scotchester, that makes sense, but with Capital Framework, we all are the team. Can we make this recommendation within CF? I think that's where the most pain is felt.

**Comment by Scotchester** [comment]
Fine with me. I think we'll just want to disable force-pushing on our master/gh-pages branch to avoid accidents that might be slightly more likely if you're pushing to upstream, rather than origin, all the time.

**Comment by jimmynotjim** [comment]
We've already had `gh-pages` accidentally get pushed because forks didn't have renamed branches, so I'm all for that even if we don't switch to branching. Also, TIL you can disable force pushes on Github, very cool.

**Comment by ascott1** [comment]
> As far as I'm concerned, I'm happy to let this be decided on a team-by-team basis, as with the decision of who merges PRs.

:+1: 

> with Capital Framework, we all are the team

Agreed. Let's disable force-pushing and give this a go? Worst case scenario we find that we prefer forks and go back to the old way.

**Comment by contolini** [comment]
Oooh I've been waiting for an opportunity to protect a branch on GitHub. Let's try it with CF.

**Comment by jimmynotjim** [comment]
Seems to be going well so far, but before we close this, I wanted to drop LGTM in here https://lgtm.co/. It prevents a PR from being merged until a specified number of sign-offs from a list of maintainers. I think we could reduce any worry about self merging with something like this in place.

**Comment by Scotchester** [comment]
I think I'd rather not enforce it automatically on most of the repos I contribute to, but if a project team wants to do it, they should feel free.

**Comment by KimberlyMunoz** [comment]
How about we describe both in the standards and have a sentence listing a few sample projects using each method, like `cfpb.github.io tends to using forking to allow non-developers to view the site using github pages, while Capital Framework uses the branching method to allow easier collaboration on feature branches.`

**Comment by ascott1** [comment]
@jimmynotjim LGTM looks really cool, but I'm with @Scotchester. Would need to grant write access to LGTM to handle merges?

**Comment by jimmynotjim** [comment]
LGTM doesn't merge automatically, it just prevents a PR from being merged until the appropriate number of sign-offs. The only reason it would need access is to add the locks and I don't think that's write access.

**Comment by contolini** [comment]
@jimmynotjim I am really into LGTM. I've been wanting to incorporate that functionality into CFPBot for awhile now.

**Comment by jimmynotjim** [comment]
Could we try it w/ CapitalFramework? We've already got protected branches there.

**Comment by contolini** [comment]
I'm down. Let's finish merging all its outstanding PRs and then we can try it.

**Comment by jimmynotjim** [comment]
This has been working out well, closing.
