### ISSUE TITLE
Libraries and frameworks

### ISSUE THREAD

**Issue by wpears** [cfpb/front-end#5]
This is an issue to discuss the merits and use of different front-end frameworks at CFPB.

Examples:
[React](http://facebook.github.io/react/)
[Angular](https://angularjs.org)
[d3](http://d3js.org)

There's a million. Let's use the good ones.

**Comment by Scotchester** [comment]
I presume from the examples given that you mean frameworks for building applications, versus things like Bootstrap, Foundation, Capital Framework, which only provide HTML/CSS/JS patterns. Is that accurate?

**Comment by wpears** [comment]
Yes indeed! The capital framework meets our needs imo on that front and I don't think that an issue here is really necessary. Any cf ideas/issues could be added to its repo

**Comment by awolfe76** [comment]
Almost sounds like a library vs framework conversation.

Personally, I'm in favor of libraries. To me these tend to be smaller, more focused solution to a specifc problem, where frameworks tend to solve several problems and are usually larger.

Would like to add [mustache.js](https://github.com/janl/mustache.js/) to the conversation too. Or one of its variations; [hogan.js](https://github.com/twitter/hogan.js), [handlebars.js](http://handlebarsjs.com/). Very handy for lightweight templates.

**Comment by mistergone** [comment]
I think we should continue to develop Capital Framework for maximum robustness. We also should start pooling all the little plugins and modules we write so that we can all draw from them. I'm a huge fan of developing our own stuff, where possible.

But we're not going to write our own Angular, or our own d3, and in those cases I'm into us using whatever gets the job done. I definitely think we should talk about it, because oftentimes I am in the dark about libraries and frameworks (because I always try to tackle things myself), so I'd sure benefit from discussing them.

**Comment by KimberlyMunoz** [comment]
We should try to have something (internal repo?) to keep track of the frameworks and libraries we are using on public sites since there's so many issues that are going to be library/framework-specific.

**Comment by wpears** [comment]
So @contolini said the following in chat:

>i think we should probably be thinking about principles and processes rather than specific frameworks
>e.g. modularity, isomorphism, code coverage, tdd, etc.
>and those paired with a given project's specific requirements can lead to a framework decision

I think this is a pretty good point. Also, I think that individual issues would likely be better places to talk about individual libraries or classes of libraries (templating, utility, etc.).

As such, I'm closing this issue. Tease out new issues if need be.


![selfie-0](http://i.imgur.com/yfOFoc9.gif)
